[theme]
primaryColor = "#ffffff"
backgroundColor = "#000000"  # Cor de fundo da página principal
secondaryBackgroundColor = "black"  # Cor de fundo para containers e o menu lateral
textColor = "orange"  # Cor do texto
font = "sans serif"

[sidebar]
backgroundColor = "black"  # Cor de fundo do menu lateral (barra lateral)
